# Generated by Django 5.0.4 on 2024-11-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryclaim',
            name='balance_id',
            field=models.CharField(blank=True, max_length=72, null=True),
        ),
        migrations.AddField(
            model_name='temporaryclaim',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='temporaryclaim',
            name='private_key',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
    ]
